### ISSUE TITLE
Missing doc on warn Pod referencing dobs volumes must be owned by statefulset

### ISSUE THREAD

**Issue by martinlevesque** [digitalocean/clusterlint#111]
Hi,

I have few warnings such as: `Pod referencing dobs volumes must be owned by statefulset`

which links to: https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors/#dobs-pod-owner

However the link don't seem correct and there don't seem to have documentation about this issue.

**Comment by varshavaradarajan** [comment]
Thanks @martinlevesque! :) We will be updating it soon.

**Comment by martinlevesque** [comment]
@varshavaradarajan awesome, thanks!

**Comment by varshavaradarajan** [comment]
@martinlevesque - https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors/#dobs-pod-owner

**Comment by martinlevesque** [comment]
@varshavaradarajan thanks for the update.

Mm that's a pretty significant breaking change. That means we can no more use deployments with volumes -> generating pods ???

I have deployments with the following spec part

```
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: www
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www
        deploymentId: "252844"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: dotenv
        image: registry.digitalocean.com/production-openode/xxxxx
        imagePullPolicy: Always
        name: www
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            ephemeral-storage: 100Mi
            memory: 100Mi
          requests:
            ephemeral-storage: 100Mi
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app/data
          name: main-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      initContainers:
      - command:
        - sh
        - -c
        - chmod 777 "/opt/app/data"
        image: busybox
        imagePullPolicy: Always
        name: init-volume
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app/data
          name: main-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: main-volume
        persistentVolumeClaim:
          claimName: main-pvc
```

How to still use Deployment, and not StatefulSet?
