### ISSUE TITLE
Disable checking for each container

### ISSUE THREAD

**Issue by valbeat** [digitalocean/clusterlint#74]
Currently, the check is invalidated by metadata.
However, this method does not allow you to disable checks on a per container basis.
Is there a way to solve this?

**Comment by adamwg** [comment]
Hi @valbeat - thanks for the question.

This is an interesting idea - I can definitely see the use for it for checks like `latest-tag` where perhaps you want to use an image with the latest tag for only one container in a pod, but still want to check the others.

The `Container` object in the k8s API doesn't have metadata, so we can't specify any annotations there. That would be the obvious way to implement this if it were an option, since it would mirror how we currently do check suppression at the pod level.

One option would be to introduce new pod annotations that specify which containers in the pod should skip certain checks. For example, maybe something like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    clusterlint.digitalocean.com/disabled-container-checks: "container1:latest-tag,container2:fully-qualified-image"
```

Does that seem reasonable?

@varshavaradarajan @timoreimann Any other ideas for how we could do this?
